@SharlmagneHenryAPI_HostAddress = http://localhost:5194

## Project Endpoints

### Get all projects
GET {{SharlmagneHenryAPI_HostAddress}}/projects/

### Get project by id
GET {{SharlmagneHenryAPI_HostAddress}}/projects/1

### Create project
POST {{SharlmagneHenryAPI_HostAddress}}/projects/
Content-Type: application/json

{
    "title": "Project 1",
    "description": "Project 1 description"
}

### Update project
PUT {{SharlmagneHenryAPI_HostAddress}}/projects/1
Content-Type: application/json

{
    "title": "Project 1",
    "description": "Project 1 description Edited"
}

### Delete project
DELETE {{SharlmagneHenryAPI_HostAddress}}/projects/3


## Skills Endpoints


### Get all skills
GET {{SharlmagneHenryAPI_HostAddress}}/skills?include=projects

### Get skill by id
GET {{SharlmagneHenryAPI_HostAddress}}/skills/5?include=children

### Create skill
POST {{SharlmagneHenryAPI_HostAddress}}/skills/
Content-Type: application/json

{
    "name": "Child Skill 4",
    "description": "Child skill 3 description"
}

### Update skill
PUT {{SharlmagneHenryAPI_HostAddress}}/skills/5
Content-Type: application/json

{
    "name": "Skill 1",
    "description": "Skill 1 description Edited"
}

### Delete skill
DELETE {{SharlmagneHenryAPI_HostAddress}}/skills/13


### Add project to skill
PATCH {{SharlmagneHenryAPI_HostAddress}}/skills/5/project/1

### Remove project from skill
DELETE {{SharlmagneHenryAPI_HostAddress}}/skills/5/project/1